name: Generar una issue al abrir un pull request y asociarla automáticamente

on:
  pull_request:
    types: 
      - opened
      - reopened

jobs:
  create_issue_and_link:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Crear issue
        run: |
          issue_id=$(gh issue create --assignee pilarAlonsoSTEMDO --title "Issue generada automáticamente al abrir un pull request" --body "Esta issue ha sido creada automáticamente al abrirse el pull request. Asignada a: @pilarAlonsoSTEMDO" | cut -d"/" -f7)
          echo "issue_id=$issue_id" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Asociar issue a pull request
        run: |
          gh pr edit ${{ github.event.number }} --body "Close #${{ env.issue_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

